name: Build and Publish Xulcan Engine

on:
  push:
    branches:
      - worldly      # 🌍 Worldly Mode: Se dispara con cada push a worldly

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/silixe/xulcan-silixe
          tags: |
            # Snapshot de la rama worldly
            type=raw,value=worldly,enable=${{ github.ref == 'refs/heads/worldly' }}
            # SHA para auditoría
            type=sha,format=short,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}