name: Build and Publish Xulcan Engine

on:
  push:
    branches:
      - main         # 🏆 Lanza la imagen 'latest'
      - develop      # 🧪 Lanza la imagen 'dev' (Tu laboratorio)
      - worldly      # 🌍 Lanza la imagen 'worldly' (Entorno real / Staging)
    tags:
      - 'v*.*.*'     # 💎 Lanza versiones oficiales (ej. v1.0.0)

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          # Usamos tu variable de secreto para que sea dinámico
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/xulcan
          tags: |
            # 1. Versiones Oficiales: Si haces tag v1.2.3, crea imagen '1.2.3'
            type=semver,pattern={{version}}
            
            # 2. Producción: Si el push es a 'main', crea imagen 'latest'
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

            # 3. Laboratorio: Si el push es a 'develop', crea imagen 'dev'
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/develop' }}

            # 4. Pruebas Reales: Si el push es a 'worldly', crea imagen 'worldly'
            type=raw,value=worldly,enable=${{ github.ref == 'refs/heads/worldly' }}

            # 5. Seguridad/Trazabilidad: Crea siempre una etiqueta con el SHA del commit
            type=sha,format=short,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}